spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PW}
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
oauth2:
  kakao:
    client_id: ${ENV_KAKAO_CLIENT_ID}
    redirect_url: ${ENV_REDIRECT_URI}
    auth_base_url: ${ENV_AUTH_BASE_URL}
    api_base_url: ${ENV_API_BASE_URL}
  google:
    client_id: ${ENV_GOOGLE_CLIENT_ID}
    redirect_url: ${ENV_GOOGLE_REDIRECT_URI}
    client_secret: ${ENV_GOOGLE_CLIENT_SECRET}
    token_base_url: ${ENV_GOOGLE_TOKEN_BASE_URL}
    auth_base_url: ${ENV_GOOGLE_AUTH_BASE_URL}
    api_base_url: ${ENV_GOOGLE_API_BASE_URL}
auth:
  jwt:
    secret: ${ENV_JWT_SECRET}
    accessTokenExpirationTime: ${ENV_JWT_EXPIRATION_TIME}