spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PW}
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
oauth2:
  kakao:
    client_id: ${ENV_KAKAO_CLIENT_ID}
    redirect_url: ${ENV_KAKAO_REDIRECT_URI}
  google:
    client_id: ${ENV_GOOGLE_CLIENT_ID}
    redirect_url: ${ENV_GOOGLE_REDIRECT_URI}
    client_secret: ${ENV_GOOGLE_CLIENT_SECRET}
auth:
  jwt:
    secret: ${ENV_JWT_SECRET}
    accessTokenExpirationTime: ${ENV_JWT_EXPIRATION_TIME}
mail:
  host: smtp.gmail.com
  port: 587
  username: ${ENV_EMAIL_NAME}
  password: ${ENV_EMAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectionTimeout: 5000
        timeout: 5000
        writeTimeout: 5000
        auth-code-expiration-millis: 1800000
kApi:
  url: ${ENV_KAPI_URL}
frontend:
  domain: ${ENV_FE_LOGIN_REDIRECT_URL}